/* Challenge:
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
Find the largest palindrome made from the product of two 3-digit numbers.
*/

/* Method:
Generate all palindromes that could possibly be generated by 2 3 digit numbers,
and check each one.

10^4 * 10^4 - 1 = 999999 is the largest, take the first part, '999' as an int
and increment it down, checking the palindrome generated from it for the
appropriate divisors.
*/

function largest_palindrome(value) {
  var stop_value = (value/10>>0); // Like floor, but faster (+ works better for negative values)
  var current_value = value;
  var i;
  while (true) {
    var n = current_value.toString();
    var test_value = parseInt(n + n.split("").reverse().join(""));
    for (i = value; i > stop_value; i--) {
      if (test_value % i == 0 && (test_value/i).toString().length == 3) {
        return test_value;
      }
    }
    current_value -= 1;
  }
}

console.log(largest_palindrome(999));
